// Helper to generate 1-9 arrays easily
const numRow = ["1","2","3","4","5","6","7","8","9"];
const numPad = ["NUM_1","NUM_2","NUM_3","NUM_4","NUM_5","NUM_6","NUM_7","NUM_8","NUM_9"];

const rawShortcuts = [
    // --- GLOBAL & FILE ---
    { key: "O", mod: "Ctrl", context: "Global", action: "Open file", details: "Opens the file browser to load an existing .flp project.", type: "kb" },
    { key: "S", mod: "Ctrl", context: "Global", action: "Save file", details: "Standard project save. Practice 'Ctrl+S' frequently to prevent data loss from unexpected crashes.", type: "kb" },
    { key: "N", mod: "Ctrl", context: "Global", action: "Save new version", details: "Creates a new numbered project file (e.g., v2, v3). Essential for 'checkpointing' before making major changes.", type: "kb" },
    { key: "S", mod: "Ctrl+Shift", context: "Global", action: "Save As...", details: "Allows you to save the current project under a different name or location.", type: "kb" },
    { key: "R", mod: "Ctrl", context: "Global", action: "Export wave file", details: "Opens the render dialog to export your song into a high-quality lossless .wav format.", type: "kb" },
    { key: "R", mod: "Ctrl+Shift", context: "Global", action: "Export mp3 file", details: "Exports your song into a compressed .mp3 format, ideal for quick sharing or streaming.", type: "kb" },
    { key: "M", mod: "Ctrl+Shift", context: "Global", action: "Export MIDI file", details: "Saves the note data of your project as a MIDI file for use in other software.", type: "kb" },
    { key: "H", mod: "Ctrl+Shift", context: "Global", action: "(Re)arrange windows", details: "Resets the positions of all open windows to the default layout.", type: "kb" },
    { key: "F12", mod: "", context: "Global", action: "Close all windows", details: "Closes all open plugin and window interfaces at once to clear screen clutter and free up system resources.", type: "kb" },
    { key: "F8", mod: "", context: "Global", action: "Open Plugin Picker", details: "A visual menu showing thumbnails of all your instruments and effects for fast loading.", type: "kb" },
    { key: "F8", mod: "Ctrl", context: "Global", action: "Open Project Picker", details: "Provides a birds-eye view of all Patterns, Audio Clips, and Automation used in the current song.", type: "kb" },
    { key: "SPACE", mod: "", context: "Global", action: "Start/Stop Playback", details: "Toggles the main transport. Pressing Stop twice resets the playhead to the start.", type: "kb" },
    { key: "SPACE", mod: "Ctrl", context: "Global", action: "Start/Pause Playback", details: "Pauses the music exactly where the playhead is rather than resetting its position.", type: "kb" },
    { key: "H", mod: "Ctrl", context: "Global", action: "Stop sound (panic)", details: "The 'Panic Switch'. Immediately kills all audio and MIDI—vital if a plugin freezes on a loud note.", type: "kb" },
    { key: "M", mod: "Ctrl", context: "Global", action: "Toggle metronome", details: "Turns the click track on or off to help you stay on beat during recording or editing.", type: "kb" },
    { key: "P", mod: "Ctrl", context: "Global", action: "Toggle metronome precount", details: "Gives you a 1-bar count-in before recording starts so you can prepare to play.", type: "kb" },
    { key: "I", mod: "Ctrl", context: "Global", action: "Toggle wait for input", details: "Playback won't start until you play a note on your MIDI controller. Great for one-man recording.", type: "kb" },
    { key: "T", mod: "Ctrl", context: "Global", action: "Toggle typing to piano keypad", details: "Allows your QWERTY keyboard to play musical notes. Right-click the icon to set specific scales.", type: "kb" },
    { key: "B", mod: "Ctrl", context: "Global", action: "Toggle blend notes", details: "When recording MIDI, new notes will merge with existing ones instead of overwriting them.", type: "kb" },
    { key: "TAB", mod: "", context: "Global", action: "Cycle nested windows", details: "Switches focus between open plugin windows, the Mixer, and the Playlist.", type: "kb" },
    { key: "ESC", mod: "", context: "Global", action: "Close a window", details: "Closes the currently focused window or plugin interface.", type: "kb" },
    { key: "F1", mod: "", context: "Global", action: "Help", details: "Opens the FL Studio online manual to the page relevant to the currently focused tool.", type: "kb" },
    { key: "F3", mod: "", context: "Global", action: "Open tool selector/options", details: "Opens a quick-menu at your mouse cursor to switch tools like Draw, Paint, or Slice.", type: "kb" },
    
    // --- WINDOW TOGGLES ---
    { key: "F5", mod: "", context: "Global", action: "Toggle Playlist", details: "Opens the main arrangement window where patterns and audio clips are sequenced.", type: "kb" },
    { key: "F6", mod: "", context: "Global", action: "Toggle Step Sequencer", details: "Opens the Channel Rack for drum programming and instrument management.", type: "kb" },
    { key: "F7", mod: "", context: "Global", action: "Toggle Piano roll", details: "Opens the advanced MIDI editor for the currently selected channel.", type: "kb" },
    { key: "F9", mod: "", context: "Global", action: "Show/hide Mixer", details: "Opens the mixer for volume balancing, routing, and adding effects.", type: "kb" },
    { key: "F10", mod: "", context: "Global", action: "Show/hide MIDI settings", details: "Quick access to your MIDI controller and input/output configuration.", type: "kb" },
    { key: "F11", mod: "", context: "Global", action: "Show/hide song info window", details: "Displays project metadata like title, author, and time spent working on the project.", type: "kb" },
    { key: "F8", mod: "Alt", context: "Global", action: "Show/hide Sample Browser", details: "Toggles the sidebar where your samples, presets, and project files are stored.", type: "kb" },
    { key: "ENTER", mod: "", context: "Global", action: "Toggle Max/Min Playlist", details: "Instantly maximizes the playlist to full screen or returns it to windowed mode.", type: "kb" },

    // --- PATTERN / TRANSPORT ---
    { key: "NUM_+", mod: "", context: "Global", action: "Next pattern", details: "Selects the next pattern in the project list.", type: "kb" },
    { key: "NUM_-", mod: "", context: "Global", action: "Previous pattern", details: "Selects the previous pattern in the project list.", type: "kb" },
    { key: "F2", mod: "", context: "Global", action: "Open name editor for pattern", details: "Rename and recolor patterns. Pressing F2 repeatedly generates random colors.", type: "kb" },
    { key: "F4", mod: "", context: "Global", action: "Next empty pattern with naming", details: "Finds the first unused pattern and prompts you to name and color it.", type: "kb" },
    { key: "F4", mod: "Ctrl", context: "Global", action: "Next empty pattern", details: "Instantly switches to the next empty pattern without any naming prompts.", type: "kb" },
    { key: "BACK", mod: "", context: "Global", action: "Toggle Line/None Snap", details: "Quickly switches between your current snap setting and 'None' for fine adjustments.", type: "kb" },
    { key: "L", mod: "", context: "Global", action: "Switch Pattern/Song mode", details: "Toggles between playing a single pattern or the entire arrangement (Playlist).", type: "kb" },
    { key: "R", mod: "", context: "Global", action: "Switch On/Off recording", details: "Arms the project for recording MIDI or audio on the next playback.", type: "kb" },
    { key: "NUM_0", mod: "", context: "Global", action: "Fast forward", details: "Moves the playhead forward quickly through the arrangement.", type: "kb" },
    { key: "NUM_/", mod: "", context: "Global", action: "Previous bar (Song mode)", details: "Jumps the playhead back by exactly one bar.", type: "kb" },
    { key: "NUM_*", mod: "", context: "Global", action: "Next bar (Song mode)", details: "Jumps the playhead forward by exactly one bar.", type: "kb" },

    // --- CHANNEL RACK ---
    { key: "0", mod: "", context: "Channel Rack", action: "Mute Toggle Channel 10", details: "Toggles the mute state for the tenth instrument in the rack.", type: "kb" },
    { key: "0", mod: "Ctrl", context: "Channel Rack", action: "Solo/UnSolo Channel 10", details: "Solos the tenth instrument in the rack, muting all others.", type: "kb" },
    { key: "UP", mod: "", context: "Channel Rack", action: "Select Channel above", details: "Moves the instrument selection highlight up.", type: "kb" },
    { key: "DOWN", mod: "", context: "Channel Rack", action: "Select Channel below", details: "Moves the instrument selection highlight down.", type: "kb" },
    { key: "PGUP", mod: "", context: "Channel Rack", action: "Select next Channel Group", details: "Jumps between custom categories like 'Drums', 'Synths', or 'Audio'.", type: "kb" },
    { key: "PGDN", mod: "", context: "Channel Rack", action: "Select previous Channel Group", details: "Jumps to the previous custom instrument category.", type: "kb" },
    { key: "DEL", mod: "Alt", context: "Channel Rack", action: "Delete selected Channel(s)", details: "Removes instruments from the project. Warning: This cannot be undone.", type: "kb" },
    { key: "DOWN", mod: "Alt", context: "Channel Rack", action: "Move selected Channel(s) down", details: "Reorders instruments in the rack by moving the selection down.", type: "kb" },
    { key: "UP", mod: "Alt", context: "Channel Rack", action: "Move selected Channel(s) up", details: "Reorders instruments in the rack by moving the selection up.", type: "kb" },
    { key: "C", mod: "Alt", context: "Channel Rack", action: "Clone selected Channels", details: "Duplicates instruments and their settings (but not their MIDI data).", type: "kb" },
    { key: "G", mod: "Alt", context: "Channel Rack", action: "Group selected Channels", details: "Prompts you to name a new group for the selected instruments to organize the rack.", type: "kb" },
    { key: "M", mod: "Alt", context: "Channel Rack", action: "Toggle Mixer Track Selectors", details: "Shows/hides the number boxes used for routing instruments to mixer tracks.", type: "kb" },
    { key: "U", mod: "Alt", context: "Channel Rack", action: "Unzip selected Channel(s)", details: "Restores 'Zipped' (collapsed) channels to their full view.", type: "kb" },
    { key: "Z", mod: "Alt", context: "Channel Rack", action: "Zip selected Channel(s)", details: "Collapses channels into tiny bars to save vertical space. Helpful for finished tracks.", type: "kb" },
    { key: "R", mod: "Ctrl+Alt", context: "Channel Rack", action: "Force restretch all Audio Clips", details: "Updates all audio clips to match a new project tempo.", type: "kb" },
    { key: "ENTER", mod: "Ctrl", context: "Channel Rack", action: "Focus Playlist", details: "Immediately brings the Playlist window to the front.", type: "kb" },
    { key: "C", mod: "Ctrl", context: "Channel Rack", action: "Copy Channel Steps/Score", details: "Copies MIDI notes or step sequencer data to the clipboard.", type: "kb" },
    { key: "L", mod: "Ctrl", context: "Channel Rack", action: "Route to free mixer track(s)", details: "Finds an empty mixer track and links the instrument to it, inheriting name and color.", type: "kb" },
    { key: "V", mod: "Ctrl", context: "Channel Rack", action: "Paste Channel Steps/Score", details: "Pastes MIDI or step data into the currently selected channel.", type: "kb" },
    { key: "X", mod: "Ctrl", context: "Channel Rack", action: "Cut Channel Steps/Score", details: "Removes data and stores it in the clipboard.", type: "kb" },
    { key: "UP", mod: "Shift", context: "Channel Rack", action: "Moves Channel selection Up", details: "Extends the selection highlight upwards.", type: "kb" },
    { key: "DOWN", mod: "Shift", context: "Channel Rack", action: "Moves Channel selection Down", details: "Extends the selection highlight downwards.", type: "kb" },
    { key: "LEFT", mod: "Ctrl+Shift", context: "Channel Rack", action: "Shift Steps Left", details: "Nudges all sequencer steps one tick to the left—perfect for adjusting timing 'shove'.", type: "kb" },
    { key: "RIGHT", mod: "Ctrl+Shift", context: "Channel Rack", action: "Shift Steps Right", details: "Nudges all sequencer steps one tick to the right.", type: "kb" },

    // --- PLAYLIST ---
    { key: "B", mod: "", context: "Playlist", action: "Paint tool", details: "Used for clicking and dragging to place multiple instances of clips or patterns.", type: "kb" },
    { key: "C", mod: "", context: "Playlist", action: "Slice tool", details: "Used to cut audio or pattern clips into smaller pieces.", type: "kb" },
    { key: "D", mod: "", context: "Playlist", action: "Delete tool", details: "Click clips to remove them from the arrangement.", type: "kb" },
    { key: "E", mod: "", context: "Playlist", action: "Select tool", details: "Used to highlight multiple clips for moving or editing.", type: "kb" },
    { key: "P", mod: "", context: "Playlist", action: "Draw tool (pencil)", details: "The default tool for placing individual clips or patterns.", type: "kb" },
    { key: "S", mod: "", context: "Playlist", action: "Slip edit tool", details: "Moves the content inside an audio clip without moving the clip's boundaries in the playlist.", type: "kb" },
    { key: "T", mod: "", context: "Playlist", action: "Mute tool", details: "Deactivates clips so they don't play, without deleting them from the arrangement.", type: "kb" },
    { key: "Y", mod: "", context: "Playlist", action: "Playback tool", details: "Click any point in the playlist to hear the arrangement from that specific spot.", type: "kb" },
    { key: "Z", mod: "", context: "Playlist", action: "Zoom tool", details: "Click to zoom in; right-click to zoom out.", type: "kb" },
    { key: "G", mod: "Alt", context: "Playlist", action: "Ungroup selection", details: "Separates clips that were previously locked together.", type: "kb" },
    { key: "M", mod: "Alt", context: "Playlist", action: "Mute selection", details: "Immediately deactivates all highlighted clips.", type: "kb" },
    { key: "P", mod: "Alt", context: "Playlist", action: "Open the Picker Panel", details: "Shows the list of all Patterns, Audio, and Automation on the left of the playlist.", type: "kb" },
    { key: "T", mod: "Alt", context: "Playlist", action: "Add Time marker", details: "Places a marker in the timeline. Useful for labeling sections like 'Verse' or 'Chorus'.", type: "kb" },
    { key: "M", mod: "Alt+Shift", context: "Playlist", action: "Unmute selection", details: "Re-activates all highlighted clips.", type: "kb" },
    { key: "A", mod: "Ctrl", context: "Playlist", action: "Select All", details: "Highlights every clip and pattern in the arrangement.", type: "kb" },
    { key: "BACK", mod: "", context: "Playlist", action: "Toggle Global Snap", details: "Quickly switches between grid-snapping and 'None' for precise clip placement.", type: "kb" },
    { key: "B", mod: "Ctrl", context: "Playlist", action: "Duplicate selection", details: "Copies selection and snaps it exactly to the end of the current selection. Ideal for looping.", type: "kb" },
    { key: "C", mod: "Ctrl", context: "Playlist", action: "Copy selection", details: "Stores highlighted clips in the clipboard.", type: "kb" },
    { key: "D", mod: "Ctrl", context: "Playlist", action: "Deselect selection", details: "Clears all highlighted clips.", type: "kb" },
    { key: "P", mod: "Ctrl", context: "Playlist", action: "Toggle Performance Mode", details: "Switches the playlist into a grid for live triggering of clips.", type: "kb" },
    { key: "V", mod: "Ctrl", context: "Playlist", action: "Paste selection", details: "Places clipboard content at the current playhead position.", type: "kb" },
    { key: "X", mod: "Ctrl", context: "Playlist", action: "Cut selection", details: "Deletes clips and stores them in the clipboard.", type: "kb" },
    { key: "C", mod: "Ctrl+Alt", context: "Playlist", action: "Consolidate to audio (from clip)", details: "Renders the selected patterns/clips into a single WAV file to save CPU power.", type: "kb" },
    { key: "C", mod: "Ctrl+Alt+Shift", context: "Playlist", action: "Consolidate audio (from start)", details: "Renders the selection into a WAV file starting from the very beginning of the track.", type: "kb" },
    { key: "G", mod: "Ctrl+Alt", context: "Playlist", action: "Grid Color", details: "Opens the color picker to change the background grid contrast.", type: "kb" },
    { key: "HOME", mod: "Ctrl+Alt", context: "Playlist", action: "Toggle Resizing from Left", details: "Unlocks the ability to drag the start of a clip to shorten or lengthen it.", type: "kb" },
    { key: "INS", mod: "Ctrl", context: "Playlist", action: "Add space at timeline selection", details: "Pushes the arrangement forward to create room for new sections like a bridge or intro.", type: "kb" },
    { key: "DEL", mod: "Ctrl", context: "Playlist", action: "Delete space according to selection", details: "Deletes a time block and pulls the rest of the arrangement back to fill the gap.", type: "kb" },
    { key: "ENTER", mod: "Ctrl", context: "Playlist", action: "Select time around selection", details: "Matches the red timeline selection exactly to the start and end of highlighted clips.", type: "kb" },
    { key: "LEFT", mod: "Ctrl", context: "Playlist", action: "Select time before selection", details: "Expands the timeline selection to the left.", type: "kb" },
    { key: "RIGHT", mod: "Ctrl", context: "Playlist", action: "Select time after selection", details: "Expands the timeline selection to the right.", type: "kb" },
    { key: "DEL", mod: "", context: "Playlist", action: "Delete selected clip/pattern", details: "Removes highlighted items from the playlist.", type: "kb" },
    { key: "HOME", mod: "", context: "Playlist", action: "Move playback marker to start", details: "Instantly jumps the playhead to the very beginning of the arrangement.", type: "kb" },
    { key: "INS", mod: "", context: "Playlist", action: "Slice Clip at mouse cursor", details: "Quickly cuts a clip exactly where the mouse is hovering.", type: "kb" },
    { key: "PGUP", mod: "", context: "Playlist", action: "Zoom in", details: "Increases horizontal zoom.", type: "kb" },
    { key: "PGDN", mod: "", context: "Playlist", action: "Zoom out", details: "Decreases horizontal zoom.", type: "kb" },
    { key: "C", mod: "Shift", context: "Playlist", action: "Select all Clips by source", details: "Highlights every instance of the currently selected pattern or audio clip.", type: "kb" },
    { key: "G", mod: "Shift", context: "Playlist", action: "Group selected Clips", details: "Locks multiple clips together so they can be moved as a single unit.", type: "kb" },
    { key: "I", mod: "Shift", context: "Playlist", action: "Invert selection", details: "Deselects current items and highlights everything else—great for clearing 'unused' clutter.", type: "kb" },
    { key: "Q", mod: "Shift", context: "Playlist", action: "Quick quantize Clip start times", details: "Snaps the start points of all selected clips to the nearest grid line.", type: "kb" },
    { key: "LEFT", mod: "Shift", context: "Playlist", action: "Move selection Left", details: "Nudges clips to the left based on the snap setting.", type: "kb" },
    { key: "RIGHT", mod: "Shift", context: "Playlist", action: "Move selection Right", details: "Nudges clips to the right.", type: "kb" },
    { key: "UP", mod: "Shift", context: "Playlist", action: "Move selection Up", details: "Moves clips to the track above.", type: "kb" },
    { key: "DOWN", mod: "Shift", context: "Playlist", action: "Move selection Down", details: "Moves clips to the track below.", type: "kb" },
    { key: "T", mod: "Alt+Shift", context: "Playlist", action: "Set Time Signature at Play head", details: "Changes the project time signature (e.g. 4/4 to 3/4) at the specific playhead position.", type: "kb" },
    { key: "M", mod: "Shift", context: "Playlist", action: "Switch stretch mode", details: "Toggle: When ON, dragging a clip edge changes its tempo; when OFF, it just trims audio.", type: "kb" },
    { key: "0", mod: "Shift", context: "Playlist", action: "Center Playlist to play-head", details: "Auto-scrolls the view so the current play position is in the middle of the screen.", type: "kb" },
    { key: "1", mod: "Shift", context: "Playlist", action: "Horizontal Zoom level 1", details: "Sets horizontal zoom to default view.", type: "kb" },
    { key: "2", mod: "Shift", context: "Playlist", action: "Horizontal Zoom level 2", details: "Sets horizontal zoom to medium view.", type: "kb" },
    { key: "3", mod: "Shift", context: "Playlist", action: "Horizontal Zoom level 3", details: "Sets horizontal zoom to close-up view.", type: "kb" },
    { key: "4", mod: "Shift", context: "Playlist", action: "Horizontal Zoom, show all", details: "Zooms out until the entire arrangement is visible.", type: "kb" },
    { key: "5", mod: "Shift", context: "Playlist", action: "Zoom to selection", details: "Auto-zooms so the highlighted clips fill the screen.", type: "kb" },
    { key: "6", mod: "Shift", context: "Playlist", action: "Fit Performance Zone", details: "Zooms to fit the area designated for performance mode triggering.", type: "kb" },

    // --- PIANO ROLL ---
    { key: "B", mod: "", context: "Piano Roll", action: "Paint tool", details: "Draws multiple notes in a row when clicking and dragging.", type: "kb" },
    { key: "C", mod: "", context: "Piano Roll", action: "Slice tool", details: "Used to cut MIDI notes into smaller parts.", type: "kb" },
    { key: "D", mod: "", context: "Piano Roll", action: "Delete tool", details: "Removes MIDI notes from the roll.", type: "kb" },
    { key: "E", mod: "", context: "Piano Roll", action: "Select tool", details: "Used to highlight multiple notes for editing.", type: "kb" },
    { key: "F", mod: "", context: "Piano Roll", action: "Show next property in event lane", details: "Cycles the bottom editor between Velocity, Pan, Pitch, and other MIDI data.", type: "kb" },
    { key: "G", mod: "", context: "Piano Roll", action: "Select the Channel above", details: "Quickly switches to the MIDI of the instrument directly above in the rack.", type: "kb" },
    { key: "H", mod: "", context: "Piano Roll", action: "Select Channel above with data", details: "Skips empty channels to find the nearest instrument above with notes.", type: "kb" },
    { key: "J", mod: "", context: "Piano Roll", action: "Select Channel below with data", details: "Skips empty channels to find the nearest instrument below with notes.", type: "kb" },
    { key: "K", mod: "", context: "Piano Roll", action: "Select the Channel below", details: "Quickly switches to the MIDI of the instrument directly below in the rack.", type: "kb" },
    { key: "M", mod: "", context: "Piano Roll", action: "Keyboard view mode (toggle)", details: "Changes how the left-side keyboard is displayed (e.g. flat vs. 3D).", type: "kb" },
    { key: "O", mod: "", context: "Piano Roll", action: "Portamento (toggle)", details: "Makes new notes play with a sliding pitch effect.", type: "kb" },
    { key: "P", mod: "", context: "Piano Roll", action: "Draw tool (pencil)", details: "Standard tool for placing individual notes.", type: "kb" },
    { key: "S", mod: "", context: "Piano Roll", action: "Slide note (toggle)", details: "Makes new notes act as slide notes, which bend the pitch of existing notes.", type: "kb" },
    { key: "T", mod: "", context: "Piano Roll", action: "Mute tool", details: "Deactivates notes without deleting them.", type: "kb" },
    { key: "Y", mod: "", context: "Piano Roll", action: "Playback tool", details: "Click to hear the MIDI score from that specific point.", type: "kb" },
    { key: "Z", mod: "", context: "Piano Roll", action: "Zoom tool", details: "Click to zoom in; right-click to zoom out on notes.", type: "kb" },
    { key: "A", mod: "Alt", context: "Piano Roll", action: "Arpeggiator", details: "Turns held chords into rhythmic sequences. Essential for synth melodies.", type: "kb" },
    { key: "B", mod: "Alt", context: "Piano Roll", action: "View note helpers", details: "Toggles ghost channels and scale highlighting.", type: "kb" },
    { key: "C", mod: "Alt", context: "Piano Roll", action: "Change color of selected note(s)", details: "Assigns a different MIDI color/channel to the highlighted notes.", type: "kb" },
    { key: "E", mod: "Alt", context: "Piano Roll", action: "Riff machine", details: "Generates random melodies and sequences based on user-defined rules.", type: "kb" },
    { key: "F", mod: "Alt", context: "Piano Roll", action: "Flam", details: "Slightly offsets the start of notes in a chord to create a 'strummed' drum or piano effect.", type: "kb" },
    { key: "G", mod: "Alt", context: "Piano Roll", action: "Ungroup selected notes", details: "Separates MIDI notes that were locked together.", type: "kb" },
    { key: "K", mod: "Alt", context: "Piano Roll", action: "Open Limit tool", details: "Forces all selected notes into a chosen Key or Scale. Fixes wrong notes instantly.", type: "kb" },
    { key: "L", mod: "Alt", context: "Piano Roll", action: "Open Articulate tool", details: "Provides control over note length and legato transitions.", type: "kb" },
    { key: "M", mod: "Alt", context: "Piano Roll", action: "Mute selection", details: "Deactivates the highlighted notes.", type: "kb" },
    { key: "N", mod: "Alt", context: "Piano Roll", action: "Switch waveform helper view", details: "Shows the audio waveform of the track in the background of the piano roll.", type: "kb" },
    { key: "O", mod: "Alt", context: "Piano Roll", action: "Open LFO tool", details: "Uses a Low Frequency Oscillator to create rhythmic patterns in note properties like velocity.", type: "kb" },
    { key: "Q", mod: "Alt", context: "Piano Roll", action: "Quantize", details: "Opens the menu to apply swing or groove templates to your MIDI data.", type: "kb" },
    { key: "R", mod: "Alt", context: "Piano Roll", action: "Open Randomize tool", details: "Adds random variations to note velocity, pan, or position for a more human feel.", type: "kb" },
    { key: "S", mod: "Alt", context: "Piano Roll", action: "Open Strum tool", details: "Slightly staggers the start times of notes in a chord to mimic a guitar performance.", type: "kb" },
    { key: "U", mod: "Alt", context: "Piano Roll", action: "Open Chop tool", details: "Slices long notes into smaller rhythmic parts based on the grid.", type: "kb" },
    { key: "V", mod: "Alt", context: "Piano Roll", action: "Ghost Channels ON/OFF", details: "Displays notes from other instruments as grey shadows to help with harmony writing.", type: "kb" },
    { key: "W", mod: "Alt", context: "Piano Roll", action: "Open Claw Machine tool", details: "Advanced note slicer that creates complex rhythmic variations and rolls.", type: "kb" },
    { key: "X", mod: "Alt", context: "Piano Roll", action: "Open Scale Levels tool", details: "Proportionally adjusts velocity or pan for the selection. Great for volume swells.", type: "kb" },
    { key: "Y", mod: "Alt", context: "Piano Roll", action: "Open Score Flipper tool", details: "Mirrors your MIDI notes horizontally or vertically.", type: "kb" },
    { key: "M", mod: "Alt+Shift", context: "Piano Roll", action: "Unmute selection", details: "Re-activates highlighted notes.", type: "kb" },
    { key: "UP", mod: "Alt", context: "Piano Roll", action: "Nudge position of note(s)", details: "Moves notes slightly Up in pitch, ignoring the snap setting.", type: "kb" },
    { key: "DOWN", mod: "Alt", context: "Piano Roll", action: "Nudge position of note(s)", details: "Moves notes slightly Down in pitch.", type: "kb" },
    { key: "LEFT", mod: "Alt", context: "Piano Roll", action: "Nudge position of note(s)", details: "Moves notes slightly Left in time.", type: "kb" },
    { key: "RIGHT", mod: "Alt", context: "Piano Roll", action: "Nudge position of note(s)", details: "Moves notes slightly Right in time.", type: "kb" },
    { key: "A", mod: "Ctrl", context: "Piano Roll", action: "Select All", details: "Highlights every note in the current score.", type: "kb" },
    { key: "B", mod: "Ctrl", context: "Piano Roll", action: "Duplicate selection (Buplicate)", details: "Copies and pastes selection exactly at the end of the previous note.", type: "kb" },
    { key: "C", mod: "Ctrl", context: "Piano Roll", action: "Copy selection", details: "Stores MIDI notes in the clipboard.", type: "kb" },
    { key: "D", mod: "Ctrl", context: "Piano Roll", action: "Deselect selection", details: "Clears MIDI highlights.", type: "kb" },
    { key: "G", mod: "Ctrl", context: "Piano Roll", action: "Glue touching notes", details: "Merges adjacent notes into a single long note.", type: "kb" },
    { key: "I", mod: "Ctrl", context: "Piano Roll", action: "Insert current controller value", details: "Writes the current setting of a linked knob into the event automation lane.", type: "kb" },
    { key: "L", mod: "Ctrl", context: "Piano Roll", action: "Quick legato", details: "Removes all gaps between notes by extending their ends to the next note start.", type: "kb" },
    { key: "M", mod: "Ctrl", context: "Piano Roll", action: "Import MIDI file", details: "Loads external MIDI data into the current channel.", type: "kb" },
    { key: "Q", mod: "Ctrl", context: "Piano Roll", action: "Quick Quantize", details: "Hard-snaps MIDI note starts to the current grid setting.", type: "kb" },
    { key: "U", mod: "Ctrl", context: "Piano Roll", action: "Quick Chop", details: "Instantly slices notes based on the current grid setting.", type: "kb" },
    { key: "V", mod: "Ctrl", context: "Piano Roll", action: "Paste selection", details: "Pastes MIDI from the clipboard.", type: "kb" },
    { key: "X", mod: "Ctrl", context: "Piano Roll", action: "Cut selection", details: "Removes notes and stores them in the clipboard.", type: "kb" },
    { key: "G", mod: "Ctrl+Alt", context: "Piano Roll", action: "Grid Color", details: "Opens the grid contrast color picker.", type: "kb" },
    { key: "HOME", mod: "Ctrl+Alt", context: "Piano Roll", action: "Allow resizing from left", details: "Enables dragging the start of a MIDI note to lengthen or shorten it.", type: "kb" },
    { key: "DEL", mod: "Ctrl", context: "Piano Roll", action: "Delete space equal to selection", details: "Deletes a block of time and pulls notes back to fill it.", type: "kb" },
    { key: "ENTER", mod: "Ctrl", context: "Piano Roll", action: "Select time around selection", details: "Matches the timeline selection to the start/end of highlighted notes.", type: "kb" },
    { key: "INS", mod: "Ctrl", context: "Piano Roll", action: "Insert space equal to selection", details: "Pushes notes forward to create a gap in the score.", type: "kb" },
    { key: "UP", mod: "Ctrl", context: "Piano Roll", action: "Transpose UP 1 Octave", details: "Jumps the highlighted notes up by 12 semitones.", type: "kb" },
    { key: "DOWN", mod: "Ctrl", context: "Piano Roll", action: "Transpose DOWN 1 Octave", details: "Jumps the highlighted notes down by 12 semitones.", type: "kb" },
    { key: "LEFT", mod: "Ctrl", context: "Piano Roll", action: "Select time before selection", details: "Expands the timeline selection to the left.", type: "kb" },
    { key: "RIGHT", mod: "Ctrl", context: "Piano Roll", action: "Select time after selection", details: "Expands the timeline selection to the right.", type: "kb" },
    { key: "DEL", mod: "", context: "Piano Roll", action: "Delete selected", details: "Removes highlighted MIDI notes.", type: "kb" },
    { key: "PGUP", mod: "", context: "Piano Roll", action: "Zoom in", details: "Increases horizontal zoom on MIDI data.", type: "kb" },
    { key: "PGDN", mod: "", context: "Piano Roll", action: "Zoom out", details: "Decreases horizontal zoom on MIDI data.", type: "kb" },
    { key: "T", mod: "Alt+Shift", context: "Piano Roll", action: "Set Time Signature", details: "Places a time signature change at the playhead position.", type: "kb" },
    { key: "V", mod: "Ctrl+Shift", context: "Piano Roll", action: "Paste from MIDI clipboard", details: "Special paste for external MIDI data.", type: "kb" },
    { key: "C", mod: "Shift", context: "Piano Roll", action: "Select by color", details: "Highlights all notes that share the current MIDI color/channel.", type: "kb" },
    { key: "D", mod: "Shift", context: "Piano Roll", action: "Discard selected note lengths", details: "Snaps note ends to the smallest possible grid unit. Resets MIDI recordings.", type: "kb" },
    { key: "F", mod: "Shift", context: "Piano Roll", action: "Cycle through note properties", details: "Changes which property (velocity, pan, etc.) the mouse wheel affects.", type: "kb" },
    { key: "G", mod: "Shift", context: "Piano Roll", action: "Group selected", details: "Locks MIDI notes together as a single unit.", type: "kb" },
    { key: "H", mod: "Shift", context: "Piano Roll", action: "Select next Channel with data", details: "Skips to the next instrument track that has notes.", type: "kb" },
    { key: "I", mod: "Shift", context: "Piano Roll", action: "Invert selection", details: "Deselects current notes and highlights all others.", type: "kb" },
    { key: "K", mod: "Shift", context: "Piano Roll", action: "Select the the next Channel", details: "Switches MIDI view to the instrument directly below in the rack.", type: "kb" },
    { key: "N", mod: "Shift", context: "Piano Roll", action: "Turn off selected chord", details: "Deactivates a chord for previewing purposes.", type: "kb" },
    { key: "M", mod: "Shift", context: "Piano Roll", action: "Select groups at random", details: "Experimental feature to highlight random groups of notes.", type: "kb" },
    { key: "R", mod: "Shift", context: "Piano Roll", action: "Select at random", details: "Experimental feature to highlight random individual notes.", type: "kb" },
    { key: "LEFT", mod: "Shift", context: "Piano Roll", action: "Move selection Left", details: "Nudges notes left based on snap setting.", type: "kb" },
    { key: "RIGHT", mod: "Shift", context: "Piano Roll", action: "Move selection Right", details: "Nudges notes right.", type: "kb" },
    { key: "UP", mod: "Shift", context: "Piano Roll", action: "Move selection Up", details: "Transposes notes up by one semitone.", type: "kb" },
    { key: "DOWN", mod: "Shift", context: "Piano Roll", action: "Move selection Down", details: "Transposes notes down by one semitone.", type: "kb" },

    // --- MIXER ---
    { key: "LEFT", mod: "Alt", context: "Mixer", action: "Move selected track(s) Left", details: "Nudges the highlighted mixer slot to the left.", type: "kb" },
    { key: "RIGHT", mod: "Alt", context: "Mixer", action: "Move selected track(s) Right", details: "Nudges the highlighted mixer slot to the right.", type: "kb" },
    { key: "L", mod: "Alt", context: "Mixer", action: "Select Channels Linked to track", details: "Instantly highlights the instruments in the Channel Rack routed here.", type: "kb" },
    { key: "W", mod: "Alt", context: "Mixer", action: "Toggle Peak-meter 'Wave' view", details: "Changes the meter view to scrolling waveforms—great for spotting transient peaks.", type: "kb" },
    { key: "ENTER", mod: "Ctrl", context: "Mixer", action: "Show/hide track properties", details: "Toggles the bottom section of the mixer showing EQ, panning, and routing.", type: "kb" },
    { key: "A", mod: "Ctrl", context: "Mixer", action: "Select all mixer tracks", details: "Highlights every slot in the mixer.", type: "kb" },
    { key: "L", mod: "Ctrl", context: "Mixer", action: "Link selected Channels to track", details: "Routes the highlighted instruments in the Channel Rack to this specific track.", type: "kb" },
    { key: "L", mod: "Ctrl+Shift", context: "Mixer", action: "Link Channels STARTING From track", details: "Batch routes multiple instruments to sequential tracks starting from the selection.", type: "kb" },
    { key: "S", mod: "Ctrl+Shift", context: "Mixer", action: "Save Mixer track state", details: "Allows you to save the entire track configuration (effects, EQ, levels) as a preset.", type: "kb" },
    { key: "F2", mod: "", context: "Mixer", action: "Rename selected mixer track", details: "Prompts for a new name and color for the track.", type: "kb" },
    { key: "S", mod: "", context: "Mixer", action: "Solo Current track", details: "Mutes all other mixer tracks except this one.", type: "kb" },
    { key: "S", mod: "Alt", context: "Mixer", action: "Alt Solo", details: "Solos the selected track AND every track routed TO/FROM it (e.g. Solo Bus + Reverb sends).", type: "kb" },
    { key: "R", mod: "Alt", context: "Mixer", action: "Render Armed tracks to .wav", details: "Starts a background recording of all 'armed' mixer tracks into audio files.", type: "kb" },

    // --- MOUSE & HYBRID ---
    { key: "Left-Click", mod: "Alt", context: "Playlist", action: "Toggle Grouped Mute", details: "Mutes/unmutes an entire group of clips at once.", type: "mouse" },
    { key: "Right-Click", mod: "Alt", context: "Playlist", action: "Audition the clip", details: "Hold Alt + Right Click to temporarily solo and hear the clip under your mouse.", type: "mouse" },
    { key: "Left-Click", mod: "Ctrl", context: "Playlist", action: "Select", details: "Standard box-selection for multiple clips.", type: "mouse" },
    { key: "Left-Click", mod: "Ctrl+Shift", context: "Playlist", action: "Add to selection", details: "Adds additional clips to the existing highlight.", type: "mouse" },
    { key: "Right-Click", mod: "Ctrl+Shift", context: "Playlist", action: "Zoom to selected Clip", details: "Instantly zooms the view so the highlighted clip fills the screen.", type: "mouse" },
    { key: "Right-Click", mod: "Ctrl", context: "Playlist", action: "Zoom on selection", details: "Drag to create a zoom box; releasing zooms to that area.", type: "mouse" },
    { key: "Double Left-Click", mod: "", context: "Playlist", action: "Open properties", details: "Opens the settings window for the pattern or audio clip.", type: "mouse" },
    { key: "Left-Click", mod: "Shift", context: "Playlist", action: "Ripple edit / Clone", details: "Hold Shift to clone a clip while dragging, or ripple-edit when resizing.", type: "mouse" },
    { key: "Right-Click", mod: "Shift", context: "Playlist", action: "Pan view / Slice & Delete", details: "Standard pan behavior or quick slice/delete depending on vertical drag.", type: "mouse" },
    { key: "Middle-Click", mod: "", context: "Playlist", action: "Pan view", details: "Hold and drag to scroll the arrangement view in any direction.", type: "mouse" },
    { key: "Right-Click", mod: "", context: "Playlist", action: "Delete tool", details: "Right-click any clip to remove it instantly.", type: "mouse" },
    { key: "Double Right-Click", mod: "", context: "Playlist", action: "Mute tool", details: "Quickly deactivates a clip.", type: "mouse" },
    { key: "Mouse-wheel", mod: "Alt+Shift", context: "Playlist", action: "Nudge Clip position", details: "Move clips horizontally in small increments, ignoring snap.", type: "mouse" },
    { key: "Mouse-wheel", mod: "Shift", context: "Playlist", action: "Re-order Clip Tracks", details: "Moves the entire track row up or down in the arrangement.", type: "mouse" },
    { key: "Mouse-wheel", mod: "Alt", context: "Piano Roll", action: "Change note property", details: "Scroll to adjust velocity, pan, or pitch of the note under the cursor.", type: "mouse" },
    { key: "Left-Click", mod: "Ctrl", context: "Piano Roll", action: "Select", details: "Standard MIDI box selection.", type: "mouse" },
    { key: "Double Left-Click", mod: "", context: "Piano Roll", action: "Open note properties", details: "Opens advanced per-note editor for timing and velocity.", type: "mouse" },
    { key: "Double Right-Click", mod: "", context: "Piano Roll", action: "Swap to Ghost Channel", details: "Double-right-click a background grey note to instantly switch to its instrument track.", type: "mouse" },
    { key: "Right-Click", mod: "Alt", context: "Piano Roll", action: "Audio preview", details: "Hold to hear the MIDI score from the mouse position.", type: "mouse" },
    { key: "Mouse-wheel", mod: "Alt+Shift", context: "Piano Roll", action: "Nudge notes", details: "Move MIDI notes horizontally in small increments without snapping.", type: "mouse" },
    { key: "Mouse-wheel", mod: "Shift", context: "Channel Rack", action: "Change Pattern / Move Channel", details: "Scroll to move the selected instrument up/down in the rack.", type: "mouse" },
    { key: "Mouse-wheel", mod: "Shift", context: "Mixer", action: "Move selected track(s) L/R", details: "Fastest way to reorder mixer slots.", type: "mouse" },
    { key: "Left-Click", mod: "Ctrl+Shift", context: "Mixer", action: "Select multiple tracks", details: "Standard multi-track selection in the mixer.", type: "mouse" },
    { key: "Left-Click", mod: "Ctrl+Alt", context: "Browser", action: "Replace Channel with item", details: "Hover a sample in the browser and use this to replace the active instrument instantly.", type: "mouse" },
    { key: "Middle-Click", mod: "", context: "Global", action: "Reset Parameter", details: "Click any knob or fader to instantly return it to its default value.", type: "mouse" }
];

// Automatically inject repeating 1-9 combinations
numRow.forEach(n => {
    rawShortcuts.push({ key: n, mod: "", context: "Global", action: `Select pattern ${n}`, details: `Switch focus to Pattern ${n}.`, type: "kb" });
    rawShortcuts.push({ key: n, mod: "Alt", context: "Global", action: `Open recent file ${n}`, details: `Load the ${n}th project from your history.`, type: "kb" });
    rawShortcuts.push({ key: n, mod: "", context: "Channel Rack", action: `Mute Tog Channel ${n}`, details: `Toggles mute for instrument ${n}.`, type: "kb" });
    rawShortcuts.push({ key: n, mod: "Ctrl", context: "Channel Rack", action: `Solo/UnSolo Channel ${n}`, details: `Solos instrument ${n} in the rack.`, type: "kb" });
});
numPad.forEach((n, idx) => {
    rawShortcuts.push({ key: n, mod: "Alt", context: "Global", action: `Change octave to ${idx+1}`, details: `Transposes your MIDI input by ${idx+1} octaves.`, type: "kb" });
});

const FL_DATA = { shortcuts: rawShortcuts };